name: build_sample_app

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

env:
  APP_CODE_PATH_HOST: ../sample_app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: git clone https://github.com/shonansurvivors/rails-deploy.git -b chapter-0-end ${APP_CODE_PATH_HOST}

      - run: make bundle-update

      - run: make yarn

      - run: make precompile

      - run: make db-migrate

      - run: make test

      - run: make up

      - uses: 8398a7/action-slack@v3.9.2
        with:
          status: ${{ job.status }}
          fields: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ALERT }}
        if: always()
